# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .hook import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "multihook",
  "mod": "index",
  "fqn": "pulumi_multihook",
  "classes": {
   "multihook:index:Hook": "Hook"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "multihook",
  "token": "pulumi:providers:multihook",
  "fqn": "pulumi_multihook",
  "class": "Provider"
 }
]
"""
)
